Repository Ajou-Travely/BE-API, pull requests merged in 2022-06, with the labels that each got.

#82 Feature/transaction
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/test/java/com/ajou/travely/service/TravelServiceTest.java
Labels: 🛠 fix, 🔧 refactor

#83 Feature/cost calculation
  src/main/java/com/ajou/travely/config/auth/LoginUserArgumentResolver.java
  src/main/java/com/ajou/travely/config/auth/SessionUser.java
  src/main/java/com/ajou/travely/controller/auth/AuthController.java
  src/main/java/com/ajou/travely/controller/cost/dto/CostCalculateRequestDto.java
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/controller/user/UserController.java
  src/main/java/com/ajou/travely/domain/UserCost.java
  src/main/java/com/ajou/travely/domain/kakao/KakaoFriend.java
  src/main/java/com/ajou/travely/domain/kakao/KakaoFriendsResponse.java
  src/main/java/com/ajou/travely/domain/kakao/KakaoMessageFailureInfo.java
  src/main/java/com/ajou/travely/domain/kakao/KakaoMessageResponse.java
  src/main/java/com/ajou/travely/domain/user/CustomUserDetails.java
  src/main/java/com/ajou/travely/exception/ErrorCode.java
  src/main/java/com/ajou/travely/exception/custom/KakaoNotAuthenticationExcpetion.java
  src/main/java/com/ajou/travely/service/AuthService.java
  src/main/java/com/ajou/travely/service/CostService.java
  src/main/java/com/ajou/travely/service/CustomUserDetailsService.java
  src/main/java/com/ajou/travely/service/JwtTokenProvider.java
  src/main/java/com/ajou/travely/service/KakaoApiService.java
  src/main/java/com/ajou/travely/service/Oauth2Service.java
  src/test/java/com/ajou/travely/service/AuthServiceTest.java
  src/test/java/com/ajou/travely/service/Oauth2ServiceTest.java
Labels: 🌈 feat

#84 Feat/travel material
  src/main/java/com/ajou/travely/controller/material/dto/MaterialCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/material/dto/MaterialResponseDto.java
  src/main/java/com/ajou/travely/controller/material/dto/MaterialUpdateRequestDto.java
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/controller/travel/dto/TravelResponseDto.java
  src/main/java/com/ajou/travely/domain/Material.java
  src/main/java/com/ajou/travely/domain/travel/Travel.java
  src/main/java/com/ajou/travely/exception/ErrorCode.java
  src/main/java/com/ajou/travely/repository/MaterialRepository.java
  src/main/java/com/ajou/travely/service/MaterialService.java
  src/test/java/com/ajou/travely/service/MaterialServiceTest.java
Labels: 🛠 fix, 🌈 feat, 📝 test

#85 feat: implement api that get posts of friends
  src/main/java/com/ajou/travely/controller/post/PostController.java
  src/main/java/com/ajou/travely/repository/PostRepository.java
  src/main/java/com/ajou/travely/service/PostService.java
Labels: 🌈 feat

#87 fix: update user response dto with add user type
  src/main/java/com/ajou/travely/controller/user/dto/UserResponseDto.java
Labels: 🛠 fix

#88 feat: add user retrieve api of admin
  src/main/java/com/ajou/travely/config/auth/SecurityConfig.java
  src/main/java/com/ajou/travely/controller/admin/UserAdminController.java
  src/main/java/com/ajou/travely/repository/UserRepository.java
  src/main/java/com/ajou/travely/service/UserService.java
Labels: 🌈 feat

#89 Fix/update user response dto
  src/main/java/com/ajou/travely/controller/post/dto/PostCreateRequestDto.java
  src/main/java/com/ajou/travely/service/PostService.java
Labels: 🛠 fix

#91 Feature/notice,event
  src/main/java/com/ajou/travely/config/WebConfig.java
  src/main/java/com/ajou/travely/controller/notice/NoticeController.java
  src/main/java/com/ajou/travely/controller/notice/dto/NoticeCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/notice/dto/NoticeResponseDto.java
  src/main/java/com/ajou/travely/controller/notice/dto/SimpleNoticeResponseDto.java
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/domain/Event.java
  src/main/java/com/ajou/travely/domain/Notice.java
  src/main/java/com/ajou/travely/domain/Photo.java
  src/main/java/com/ajou/travely/exception/ErrorCode.java
  src/main/java/com/ajou/travely/repository/NoticeRepository.java
  src/main/java/com/ajou/travely/service/NoticeService.java
  src/main/java/com/ajou/travely/service/PhotoService.java
  src/test/java/com/ajou/travely/service/NoticeServiceTest.java
Labels: 🛠 fix, 🌈 feat, 📝 test

#94 refactor: add place name and url to PostResponseDto
  src/main/java/com/ajou/travely/controller/post/dto/PostResponseDto.java
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/domain/Email.java
  src/main/java/com/ajou/travely/domain/Post.java
  src/main/java/com/ajou/travely/repository/PostRepository.java
Labels: 🔧 refactor

#95 Feature/notice,event
  src/main/java/com/ajou/travely/controller/event/EventController.java
  src/main/java/com/ajou/travely/controller/event/dto/EventUpdateDto.java
  src/main/java/com/ajou/travely/controller/notice/NoticeController.java
  src/main/java/com/ajou/travely/controller/notice/dto/NoticeUpdateDto.java
  src/main/java/com/ajou/travely/domain/Event.java
  src/main/java/com/ajou/travely/domain/Notice.java
  src/main/java/com/ajou/travely/domain/Photo.java
  src/main/java/com/ajou/travely/service/EventService.java
  src/main/java/com/ajou/travely/service/NoticeService.java
Labels: 🌈 feat
