Repository Ajou-Travely/BE-API, pull requests merged in 2022-05, with the labels that each got.

#22 Feature/place schedule basic
  .gitignore
  src/main/java/com/ajou/travely/controller/place/PlaceController.java
  src/main/java/com/ajou/travely/controller/place/dto/PlaceCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/place/dto/PlaceResponseDto.java
  src/main/java/com/ajou/travely/controller/scheduler/SchedulerController.java
  src/main/java/com/ajou/travely/controller/scheduler/dto/ScheduleCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/scheduler/dto/ScheduleResponseDto.java
  src/main/java/com/ajou/travely/controller/travel/dto/TravelCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/travel/dto/TravelResponseDto.java
  src/main/java/com/ajou/travely/domain/Place.java
  src/main/java/com/ajou/travely/domain/Schedule.java
  src/main/java/com/ajou/travely/domain/Travel.java
  src/main/java/com/ajou/travely/domain/user/User.java
  src/main/java/com/ajou/travely/repository/PlaceRepository.java
  src/main/java/com/ajou/travely/repository/ScheduleRepository.java
  src/main/java/com/ajou/travely/service/PlaceService.java
  src/main/java/com/ajou/travely/service/ScheduleService.java
  src/main/java/com/ajou/travely/service/TravelService.java
  src/main/java/com/ajou/travely/service/UserService.java
  src/test/java/com/ajou/travely/service/PlaceServiceTest.java
  src/test/java/com/ajou/travely/service/ScheduleServiceTest.java
  src/test/java/com/ajou/travely/service/TravelServiceTest.java
Labels: 🌈 feat, 🔧 refactor, 📝 test

#24 Feature/create costs
  src/main/java/com/ajou/travely/config/CustomAuthentication.java
  src/main/java/com/ajou/travely/controller/cost/CostController.java
  src/main/java/com/ajou/travely/controller/cost/dto/CostCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/cost/dto/CostResponseDto.java
  src/main/java/com/ajou/travely/domain/Cost.java
  src/main/java/com/ajou/travely/domain/UserCost.java
  src/main/java/com/ajou/travely/service/CostService.java
  src/test/java/com/ajou/travely/service/AuthServiceTest.java
  src/test/java/com/ajou/travely/service/CostServiceTest.java
Labels: 🌈 feat, 🔧 refactor, 📝 test, ✅ reviewed

#25 Feature/get cost,costs
  src/main/java/com/ajou/travely/controller/cost/CostController.java
  src/main/java/com/ajou/travely/controller/cost/dto/CostCreateResponseDto.java
  src/main/java/com/ajou/travely/controller/cost/dto/CostResponseDto.java
  src/main/java/com/ajou/travely/controller/cost/dto/UserCostResponseDto.java
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/controller/travel/dto/SimpleCostResponseDto.java
  src/main/java/com/ajou/travely/controller/user/dto/SimpleUserInfoDto.java
  src/main/java/com/ajou/travely/repository/CostRepository.java
  src/main/java/com/ajou/travely/repository/UserRepository.java
  src/main/java/com/ajou/travely/service/CostService.java
  src/main/java/com/ajou/travely/service/TravelService.java
  src/test/java/com/ajou/travely/service/CostServiceTest.java
  src/test/java/com/ajou/travely/service/TravelServiceTest.java
Labels: 🌈 feat, 🔧 refactor, 📝 test

#26 Feature/post photo basic
  src/main/java/com/ajou/travely/controller/post/PostController.java
  src/main/java/com/ajou/travely/controller/post/dto/CommentResponseDto.java
  src/main/java/com/ajou/travely/controller/post/dto/PostCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/post/dto/PostResponseDto.java
  src/main/java/com/ajou/travely/controller/post/dto/PostUpdateRequestDto.java
  src/main/java/com/ajou/travely/controller/post/dto/SimplePhotoResponseDto.java
  src/main/java/com/ajou/travely/domain/Photo.java
  src/main/java/com/ajou/travely/domain/Post.java
  src/main/java/com/ajou/travely/domain/user/User.java
  src/main/java/com/ajou/travely/repository/PhotoRepository.java
  src/main/java/com/ajou/travely/service/PostService.java
  src/main/java/com/ajou/travely/service/UserService.java
  src/test/java/com/ajou/travely/domain/post/PostRepositoryTest.java
  src/test/java/com/ajou/travely/service/PostServiceTest.java
  src/test/java/com/ajou/travely/service/ScheduleServiceTest.java
Labels: 🌈 feat, 📝 test

#30 feature/oauth_login_block_redirect_to_signup_with_no_email
  src/main/java/com/ajou/travely/service/AuthService.java
  src/main/java/com/ajou/travely/service/Oauth2Service.java
  src/test/java/com/ajou/travely/service/AuthServiceTest.java
  src/test/java/com/ajou/travely/service/CostServiceTest.java
  src/test/java/com/ajou/travely/service/Oauth2ServiceTest.java
Labels: 🌈 feat, 📝 test

#27 Feature/branch base 및 Travel 리팩토링
  src/main/java/com/ajou/travely/TravelyApplication.java
  src/main/java/com/ajou/travely/controller/CostsResponseDto.java
  src/main/java/com/ajou/travely/controller/place/dto/SimplePlaceResponseDto.java
  src/main/java/com/ajou/travely/controller/schedule/ScheduleController.java
  src/main/java/com/ajou/travely/controller/schedule/dto/ScheduleCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/schedule/dto/ScheduleResponseDto.java
  src/main/java/com/ajou/travely/controller/schedule/dto/ScheduleUpdateRequestDto.java
  src/main/java/com/ajou/travely/controller/schedule/dto/SimpleScheduleResponseDto.java
  src/main/java/com/ajou/travely/controller/scheduler/SchedulerController.java
  src/main/java/com/ajou/travely/controller/scheduler/dto/ScheduleCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/scheduler/dto/ScheduleResponseDto.java
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/controller/travel/dto/SimpleTravelResponseDto.java
  src/main/java/com/ajou/travely/controller/travel/dto/TravelCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/travel/dto/TravelResponseDto.java
  src/main/java/com/ajou/travely/domain/Branch.java
  src/main/java/com/ajou/travely/domain/Cost.java
  src/main/java/com/ajou/travely/domain/Schedule.java
  src/main/java/com/ajou/travely/domain/Travel.java
  src/main/java/com/ajou/travely/domain/UserTravel.java
  src/main/java/com/ajou/travely/repository/BranchRepository.java
  src/main/java/com/ajou/travely/repository/CostRepository.java
  src/main/java/com/ajou/travely/repository/ScheduleRepository.java
  src/main/java/com/ajou/travely/repository/TravelRepository.java
  src/main/java/com/ajou/travely/service/Oauth2Service.java
  src/main/java/com/ajou/travely/service/ScheduleService.java
  src/main/java/com/ajou/travely/service/TravelService.java
  src/test/java/com/ajou/travely/service/CostServiceTest.java
  src/test/java/com/ajou/travely/service/ScheduleServiceTest.java
  src/test/java/com/ajou/travely/service/TravelServiceTest.java
Labels: 🛠 fix, 🔧 refactor

#32 feat: shceulde update test 구현
  src/main/java/com/ajou/travely/controller/schedule/ScheduleController.java
  src/main/java/com/ajou/travely/controller/schedule/dto/ScheduleUpdateRequestDto.java
  src/main/java/com/ajou/travely/service/ScheduleService.java
  src/test/java/com/ajou/travely/service/ScheduleServiceTest.java
  src/test/java/com/ajou/travely/service/TravelServiceTest.java
Labels: 🌈 feat

#31 Feature/place management
  src/main/java/com/ajou/travely/controller/place/PlaceController.java
  src/main/java/com/ajou/travely/controller/place/dto/PlaceCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/place/dto/PlaceResponseDto.java
  src/main/java/com/ajou/travely/controller/schedule/ScheduleController.java
  src/main/java/com/ajou/travely/controller/schedule/dto/ScheduleCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/schedule/dto/ScheduleUpdateRequestDto.java
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/domain/Place.java
  src/main/java/com/ajou/travely/repository/PlaceRepository.java
  src/main/java/com/ajou/travely/service/PlaceService.java
  src/main/java/com/ajou/travely/service/ScheduleService.java
  src/test/java/com/ajou/travely/domain/post/PostRepositoryTest.java
  src/test/java/com/ajou/travely/service/AuthServiceTest.java
  src/test/java/com/ajou/travely/service/PlaceServiceTest.java
  src/test/java/com/ajou/travely/service/PostServiceTest.java
  src/test/java/com/ajou/travely/service/ScheduleServiceTest.java
  src/test/java/com/ajou/travely/service/TravelServiceTest.java
Labels: 🔧 refactor

#37 Feature/cost update,delete
  src/main/java/com/ajou/travely/controller/cost/CostController.java
  src/main/java/com/ajou/travely/controller/cost/dto/CostResponseDto.java
  src/main/java/com/ajou/travely/controller/cost/dto/CostUpdateDto.java
  src/main/java/com/ajou/travely/controller/cost/dto/CostUpdateInfoDto.java
  src/main/java/com/ajou/travely/domain/Cost.java
  src/main/java/com/ajou/travely/domain/UserCost.java
  src/main/java/com/ajou/travely/repository/UserCostRepository.java
  src/main/java/com/ajou/travely/service/CostService.java
  src/test/java/com/ajou/travely/service/CostServiceTest.java
Labels: 🌈 feat, 🔧 refactor, 📝 test

#33 Feature/exception
  src/main/java/com/ajou/travely/controller/CostsResponseDto.java
  src/main/java/com/ajou/travely/exception/ErrorCode.java
  src/main/java/com/ajou/travely/exception/ErrorResponse.java
  src/main/java/com/ajou/travely/exception/GlobalExceptionHandler.java
  src/main/java/com/ajou/travely/exception/custom/RecordNotFoundException.java
  src/main/java/com/ajou/travely/service/CostService.java
  src/main/java/com/ajou/travely/service/PlaceService.java
  src/main/java/com/ajou/travely/service/PostService.java
  src/main/java/com/ajou/travely/service/ScheduleService.java
  src/main/java/com/ajou/travely/service/TravelService.java
  src/main/java/com/ajou/travely/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/ajou/travely/service/PlaceServiceTest.java
  src/test/java/com/ajou/travely/service/TravelServiceTest.java
Labels: 🌈 feat

#39 Feature/get session user
  src/main/java/com/ajou/travely/config/WebConfig.java
  src/main/java/com/ajou/travely/config/auth/CustomAuthentication.java
  src/main/java/com/ajou/travely/config/auth/LoginUser.java
  src/main/java/com/ajou/travely/config/auth/LoginUserArgumentResolver.java
  src/main/java/com/ajou/travely/config/auth/SecurityConfig.java
  src/main/java/com/ajou/travely/config/auth/SessionUser.java
  src/main/java/com/ajou/travely/controller/auth/AuthController.java
  src/main/java/com/ajou/travely/domain/user/User.java
  src/main/java/com/ajou/travely/service/Oauth2Service.java
Labels: 🌈 feat, 🔧 refactor

#41 Feature/invitation
  build.gradle
  src/main/java/com/ajou/travely/config/MailConfig.java
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/controller/travel/dto/TravelInviteRequestDto.java
  src/main/java/com/ajou/travely/domain/Email.java
  src/main/java/com/ajou/travely/domain/Invitation.java
  src/main/java/com/ajou/travely/repository/InvitationRepository.java
  src/main/java/com/ajou/travely/service/CustomMailSender.java
  src/main/java/com/ajou/travely/service/TravelService.java
  src/main/resources/application-domain.yml
  src/main/resources/application.yml
  src/test/java/com/ajou/travely/TravelyApplicationTests.java
  src/test/java/com/ajou/travely/controller/user/UserControllerTest.java
  src/test/java/com/ajou/travely/domain/post/PostRepositoryTest.java
  src/test/java/com/ajou/travely/service/AuthServiceTest.java
  src/test/java/com/ajou/travely/service/CostServiceTest.java
  src/test/java/com/ajou/travely/service/Oauth2ServiceTest.java
  src/test/java/com/ajou/travely/service/PlaceServiceTest.java
  src/test/java/com/ajou/travely/service/PostServiceTest.java
  src/test/java/com/ajou/travely/service/ScheduleServiceTest.java
  src/test/java/com/ajou/travely/service/TravelServiceTest.java
  src/test/resources/application-domain.yml
  src/test/resources/application.yml
Labels: 🌈 feat

#34 Fix/photo s3 upload
  .gitignore
  build.gradle
  src/main/java/com/ajou/travely/config/AwsS3Config.java
  src/main/java/com/ajou/travely/config/auth/SecurityConfig.java
  src/main/java/com/ajou/travely/controller/AwsS3Controller.java
  src/main/java/com/ajou/travely/controller/photo/dto/SimplePhotoResponseDto.java
  src/main/java/com/ajou/travely/controller/post/PostController.java
  src/main/java/com/ajou/travely/controller/post/dto/PostCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/post/dto/PostResponseDto.java
  src/main/java/com/ajou/travely/controller/post/dto/PostUpdateRequestDto.java
  src/main/java/com/ajou/travely/domain/Photo.java
  src/main/java/com/ajou/travely/domain/Post.java
  src/main/java/com/ajou/travely/repository/PhotoRepository.java
  src/main/java/com/ajou/travely/service/AwsS3Service.java
  src/main/java/com/ajou/travely/service/PhotoService.java
  src/main/java/com/ajou/travely/service/PostService.java
  src/main/resources/application.yml
  src/test/java/com/ajou/travely/controller/user/UserControllerTest.java
  src/test/java/com/ajou/travely/domain/post/PostRepositoryTest.java
  src/test/java/com/ajou/travely/service/PostServiceTest.java
  src/test/resources/application.yml
Labels: 🛠 fix, 🌈 feat

#44 Feature/set schedule order
  src/main/java/com/ajou/travely/controller/schedule/dto/ScheduleUpdateRequestDto.java
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/controller/travel/dto/ScheduleOrderUpdateRequestDto.java
  src/main/java/com/ajou/travely/controller/travel/dto/TravelResponseDto.java
  src/main/java/com/ajou/travely/controller/travel/dto/TravelUpdateRequestDto.java
  src/main/java/com/ajou/travely/domain/Travel.java
  src/main/java/com/ajou/travely/service/ScheduleService.java
  src/main/java/com/ajou/travely/service/TravelService.java
  src/main/resources/application.yml
Labels: 🌈 feat

#45 Refactor/login jwt
  build.gradle
  src/main/java/com/ajou/travely/config/auth/JwtAuthenticationFilter.java
  src/main/java/com/ajou/travely/config/auth/LoginUserArgumentResolver.java
  src/main/java/com/ajou/travely/config/auth/SecurityConfig.java
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/controller/travel/dto/SimpleTravelResponseDto.java
  src/main/java/com/ajou/travely/domain/user/CustomUserDetails.java
  src/main/java/com/ajou/travely/service/AuthService.java
  src/main/java/com/ajou/travely/service/CustomUserDetailsService.java
  src/main/java/com/ajou/travely/service/JwtTokenProvider.java
  src/main/java/com/ajou/travely/service/Oauth2Service.java
  src/main/resources/application.yml
  src/test/java/com/ajou/travely/repository/PostRepositoryTest.java
  src/test/java/com/ajou/travely/service/AuthServiceTest.java
  src/test/java/com/ajou/travely/service/Oauth2ServiceTest.java
  src/test/resources/application.yml
Labels: 🌈 feat, 🔧 refactor

#48 refactor/jwt-login2
  src/main/java/com/ajou/travely/config/SwaggerConfig.java
  src/main/java/com/ajou/travely/config/auth/JwtAuthenticationFilter.java
  src/main/java/com/ajou/travely/config/auth/LoginUserArgumentResolver.java
  src/main/java/com/ajou/travely/service/JwtTokenProvider.java
  src/main/resources/application.yml
Labels: 🌈 feat, 🔧 refactor

#49 refactor: create pagination format and apply to travel list
  src/main/java/com/ajou/travely/controller/travel/dto/ResponseWithPagination.java
  src/main/java/com/ajou/travely/controller/user/UserController.java
Labels: 🔧 refactor

#50 Feature/show my info
  src/main/java/com/ajou/travely/controller/common/ResponseWithPagination.java
  src/main/java/com/ajou/travely/controller/schedule/dto/ScheduleCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/user/UserController.java
  src/main/java/com/ajou/travely/controller/user/dto/UserCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/user/dto/UserResponseDto.java
  src/main/java/com/ajou/travely/domain/user/Sex.java
  src/main/java/com/ajou/travely/domain/user/User.java
  src/main/java/com/ajou/travely/service/UserService.java
  src/test/java/com/ajou/travely/service/CostServiceTest.java
  src/test/java/com/ajou/travely/service/UserServiceTest.java
Labels: 🌈 feat

#54 refactor: change place column name
  src/main/java/com/ajou/travely/controller/place/dto/PlaceCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/place/dto/PlaceResponseDto.java
  src/main/java/com/ajou/travely/controller/place/dto/SimplePlaceResponseDto.java
  src/main/java/com/ajou/travely/domain/Place.java
  src/main/java/com/ajou/travely/service/PlaceService.java
  src/main/java/com/ajou/travely/service/ScheduleService.java
  src/test/java/com/ajou/travely/repository/PostRepositoryTest.java
  src/test/java/com/ajou/travely/service/PlaceServiceTest.java
  src/test/java/com/ajou/travely/service/ScheduleServiceTest.java
  src/test/java/com/ajou/travely/service/TravelServiceTest.java
Labels: 🔧 refactor

#57 Feature/accept or reject invitation
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/domain/Invitation.java
  src/main/java/com/ajou/travely/repository/InvitationRepository.java
  src/main/java/com/ajou/travely/service/InvitationService.java
  src/main/java/com/ajou/travely/service/TravelService.java
  src/test/java/com/ajou/travely/service/TravelServiceTest.java
Labels: 🌈 feat, 🔧 refactor, 📝 test

#61 Feature/id password login
  src/main/java/com/ajou/travely/config/auth/SecurityConfig.java
  src/main/java/com/ajou/travely/controller/auth/AuthController.java
  src/main/java/com/ajou/travely/controller/auth/dto/EmailPasswordInputDto.java
  src/main/java/com/ajou/travely/controller/user/dto/UserCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/user/dto/UserResponseDto.java
  src/main/java/com/ajou/travely/domain/user/User.java
  src/main/java/com/ajou/travely/exception/ErrorCode.java
  src/main/java/com/ajou/travely/exception/GlobalExceptionHandler.java
  src/main/java/com/ajou/travely/exception/custom/InvalidPasswordException.java
  src/main/java/com/ajou/travely/repository/UserRepository.java
  src/main/java/com/ajou/travely/service/AuthService.java
  src/main/java/com/ajou/travely/service/UserService.java
  src/test/java/com/ajou/travely/service/AuthServiceTest.java
  src/test/java/com/ajou/travely/service/CostServiceTest.java
Labels: 🛠 fix, 🌈 feat, 🔧 refactor, 📝 test

#62 Fix/fix pagination meta data
  src/main/java/com/ajou/travely/controller/user/UserController.java
  src/main/java/com/ajou/travely/repository/UserRepository.java
  src/main/java/com/ajou/travely/service/UserService.java
  src/test/java/com/ajou/travely/service/TravelServiceTest.java
Labels: 🛠 fix

#63 refactor: set - travecl - api
  src/main/java/com/ajou/travely/controller/cost/CostController.java
  src/main/java/com/ajou/travely/controller/schedule/ScheduleController.java
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/controller/user/UserController.java
Labels: 🔧 refactor

#65 refactor: cleanup cost legacy
  src/main/java/com/ajou/travely/config/WebConfig.java
  src/main/java/com/ajou/travely/controller/auth/AuthController.java
  src/main/java/com/ajou/travely/controller/cost/dto/CostCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/cost/dto/CostCreateResponseDto.java
  src/main/java/com/ajou/travely/controller/cost/dto/CostResponseDto.java
  src/main/java/com/ajou/travely/controller/cost/dto/CostUpdateDto.java
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/domain/Cost.java
  src/main/java/com/ajou/travely/service/CostService.java
  src/test/java/com/ajou/travely/service/CostServiceTest.java
  src/test/java/com/ajou/travely/service/TravelServiceTest.java
Labels: 🔧 refactor, 📝 test

#67 chore: add mail secret key
  script/deploy.sh
  src/main/java/com/ajou/travely/service/CostService.java
  src/main/resources/application.yml
Labels: chore

#64 Feat/add validation user join travel
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/domain/Invitation.java
  src/main/java/com/ajou/travely/repository/InvitationRepository.java
  src/main/java/com/ajou/travely/service/TravelService.java
  src/main/resources/application-domain.yml
  src/main/resources/application.yml
  src/test/java/com/ajou/travely/service/TravelServiceTest.java
  src/test/resources/application-domain.yml
  src/test/resources/application.yml
Labels: 🛠 fix, 🔧 refactor

#68 refactor/login-failure-handling
  src/main/java/com/ajou/travely/controller/auth/AuthController.java
  src/main/java/com/ajou/travely/controller/auth/dto/LoginSuccessResponseDto.java
  src/main/java/com/ajou/travely/service/AuthService.java
  src/main/resources/application.yml
  src/test/java/com/ajou/travely/service/AuthServiceTest.java
Labels: 📄 docs, 🔧 refactor, chore

#71 Refactor/travel schedule order
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/controller/travel/dto/TravelResponseDto.java
  src/main/java/com/ajou/travely/converter/ScheduleOrderConverter.java
  src/main/java/com/ajou/travely/domain/travel/Travel.java
  src/main/java/com/ajou/travely/service/ScheduleService.java
  src/main/java/com/ajou/travely/service/TravelService.java
Labels: 🔧 refactor

#55 Feature/travel authorization
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/exception/ErrorCode.java
  src/main/java/com/ajou/travely/exception/GlobalExceptionHandler.java
  src/main/java/com/ajou/travely/exception/custom/UnauthorizedException.java
  src/main/java/com/ajou/travely/repository/TravelRepository.java
  src/main/java/com/ajou/travely/service/TravelService.java
  src/test/java/com/ajou/travely/service/TravelServiceTest.java
Labels: 🌈 feat, issue

#72 Feature/friends pagination
  src/main/java/com/ajou/travely/controller/user/UserController.java
  src/main/java/com/ajou/travely/converter/ScheduleOrderConverter.java
  src/main/java/com/ajou/travely/repository/FriendRepository.java
  src/main/java/com/ajou/travely/service/UserService.java
  src/test/java/com/ajou/travely/service/UserServiceTest.java
Labels: 🌈 feat

#73 feat: implement cancel friend request
  src/main/java/com/ajou/travely/controller/user/UserController.java
  src/main/java/com/ajou/travely/domain/user/User.java
  src/main/java/com/ajou/travely/service/TravelService.java
  src/main/java/com/ajou/travely/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/import.sql
  src/test/java/com/ajou/travely/service/TravelServiceTest.java
  src/test/java/com/ajou/travely/service/UserServiceTest.java
Labels: 🌈 feat, 🔧 refactor, 📝 test

#76 feat: add budget field to travel entity
  src/main/java/com/ajou/travely/controller/travel/dto/TravelResponseDto.java
  src/main/java/com/ajou/travely/controller/travel/dto/TravelUpdateRequestDto.java
  src/main/java/com/ajou/travely/domain/travel/Travel.java
  src/test/java/com/ajou/travely/service/TravelServiceTest.java
Labels: 🌈 feat

#77 Refactor/travel date structure
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/controller/travel/dto/TravelDateTitleUpdateRequestDto.java
  src/main/java/com/ajou/travely/controller/travel/dto/TravelDateUpdateRequestDto.java
  src/main/java/com/ajou/travely/domain/travel/TravelDate.java
  src/main/java/com/ajou/travely/repository/TravelDateRepository.java
  src/main/java/com/ajou/travely/service/TravelService.java
  src/test/java/com/ajou/travely/service/CostServiceTest.java
  src/test/java/com/ajou/travely/service/ScheduleServiceTest.java
  src/test/java/com/ajou/travely/service/TravelServiceTest.java
  src/test/resources/application.yml
Labels: 🌈 feat, 🔧 refactor, 📝 test

#78 Fix/add schedule photos
  src/main/java/com/ajou/travely/controller/schedule/dto/SimpleScheduleResponseDto.java
  src/main/java/com/ajou/travely/controller/schedulePhoto/dto/SchedulePhotoResponseDto.java
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/controller/travel/dto/SimpleTravelDateResponseDto.java
  src/main/java/com/ajou/travely/domain/Schedule.java
  src/main/java/com/ajou/travely/domain/SchedulePhoto.java
  src/main/java/com/ajou/travely/repository/SchedulePhotoRepository.java
  src/main/java/com/ajou/travely/service/ScheduleService.java
  src/main/java/com/ajou/travely/service/TravelService.java
  src/test/java/com/ajou/travely/service/ScheduleServiceTest.java
Labels: 🌈 feat
