Repository Ajou-Travely/BE-API, pull requests merged in 2022-04, with the labels that each got.

#9 Feature/create travel controller
  build.gradle
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/domain/Travel.java
  src/test/java/com/ajou/travely/controller/travel/TravelApiControllerTest.java
Labels: 🌈feat

#10 Fix: fix autoincrement entity id strategy
  src/main/java/com/ajou/travely/domain/Branch.java
  src/main/java/com/ajou/travely/domain/Comment.java
  src/main/java/com/ajou/travely/domain/Cost.java
  src/main/java/com/ajou/travely/domain/Payment.java
  src/main/java/com/ajou/travely/domain/Photo.java
  src/main/java/com/ajou/travely/domain/Place.java
  src/main/java/com/ajou/travely/domain/Post.java
  src/main/java/com/ajou/travely/domain/Reservation.java
  src/main/java/com/ajou/travely/domain/Schedule.java
  src/main/java/com/ajou/travely/domain/UserCost.java
  src/main/java/com/ajou/travely/domain/UserTravel.java
  src/main/java/com/ajou/travely/repository/JpaTravelRepository.java
Labels: fix

#13 Docs/swagger setting
  build.gradle
  src/main/java/com/ajou/travely/config/SwaggerConfig.java
  src/main/java/com/ajou/travely/domain/Post.java
  src/main/java/com/ajou/travely/repository/UserTravel.java
  src/main/java/com/ajou/travely/repository/UserTravelRepository.java
  src/main/resources/application.yml
Labels: 🛠 fix, chore

#15 test: add travel repository test
  src/main/java/com/ajou/travely/domain/Travel.java
  src/test/java/com/ajou/travely/domain/travel/TravelRepositoryTest.java
Labels: 📝 test

#16 feature/kakao login
  build.gradle
  src/main/java/com/ajou/travely/config/CorsConfig.java
  src/main/java/com/ajou/travely/config/CustomAuthentication.java
  src/main/java/com/ajou/travely/config/RestTemplateConfig.java
  src/main/java/com/ajou/travely/config/SecurityConfig.java
  src/main/java/com/ajou/travely/controller/auth/AuthController.java
  src/main/java/com/ajou/travely/controller/travel/dto/user/UserCreateRequestDto.java
  src/main/java/com/ajou/travely/domain/AuthorizationKakao.java
  src/main/java/com/ajou/travely/domain/user/User.java
  src/main/java/com/ajou/travely/repository/UserRepository.java
  src/main/java/com/ajou/travely/service/AuthService.java
  src/main/java/com/ajou/travely/service/Oauth2Service.java
  src/main/resources/application.yml
  src/test/java/com/ajou/travely/service/Oauth2ServiceTest.java
  src/test/java/com/ajou/travely/service/TravelServiceTest.java
Labels: 🌈 feat, 📝 test

#18 Refactor/set entity dto structure
  .gitignore
  src/main/java/com/ajou/travely/controller/travel/TravelController.java
  src/main/java/com/ajou/travely/controller/travel/dto/TravelCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/travel/dto/TravelResponseDto.java
  src/main/java/com/ajou/travely/controller/travel/dto/user/SimpleUserInfoDto.java
  src/main/java/com/ajou/travely/controller/travel/dto/user/UserCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/user/UserController.java
  src/main/java/com/ajou/travely/controller/user/dto/SimpleUserInfoDto.java
  src/main/java/com/ajou/travely/controller/user/dto/UserCreateRequestDto.java
  src/main/java/com/ajou/travely/controller/user/dto/UserResponseInfoDto.java
  src/main/java/com/ajou/travely/domain/Branch.java
  src/main/java/com/ajou/travely/domain/Comment.java
  src/main/java/com/ajou/travely/domain/Cost.java
  src/main/java/com/ajou/travely/domain/Payment.java
  src/main/java/com/ajou/travely/domain/Photo.java
  src/main/java/com/ajou/travely/domain/Place.java
  src/main/java/com/ajou/travely/domain/Post.java
  src/main/java/com/ajou/travely/domain/Reservation.java
  src/main/java/com/ajou/travely/domain/Schedule.java
  src/main/java/com/ajou/travely/domain/Travel.java
  src/main/java/com/ajou/travely/domain/UserCost.java
  src/main/java/com/ajou/travely/domain/UserTravel.java
  src/main/java/com/ajou/travely/service/TravelService.java
  src/main/java/com/ajou/travely/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/ajou/travely/service/TravelServiceTest.java
  src/test/resources/application.yml
Labels: 🔧 refactor, ✅ reviewed

#19 refactor/login
  src/main/java/com/ajou/travely/TravelyApplication.java
  src/main/java/com/ajou/travely/config/CustomAuthentication.java
  src/main/java/com/ajou/travely/config/SecurityConfig.java
  src/main/java/com/ajou/travely/controller/auth/AuthController.java
  src/main/java/com/ajou/travely/controller/user/UserController.java
  src/main/java/com/ajou/travely/service/Oauth2Service.java
  src/test/java/com/ajou/travely/controller/user/UserControllerTest.java
  src/test/java/com/ajou/travely/service/Oauth2ServiceTest.java
Labels: 🔧 refactor

#20 feature/get-signedIn-user-id
  src/main/java/com/ajou/travely/service/AuthService.java
  src/test/java/com/ajou/travely/service/AuthServiceTest.java
Labels: 🌈 feat, 📝 test
